//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Ventanas.rc
//
#define IDD_D_InicioSesion              101
#define IDD_IS_CB_Comercio              101
#define IDD_D_RegistroAdmin             103
#define IDD_D_VPantallaPrincipal        107
#define IDD_D_ActualizarUsuario         109
#define IDD_D_AltaAdmin                 113
#define IDD_D_AltaCajero                115
#define IDD_D_ListadoAdmin              117
#define IDD_D_ListaCajeros              119
#define IDD_D_BajaAdmin                 121
#define IDD_D_BajaCajero                123
#define IDD_D_ActualizarAdmin           125
#define IDD_D_ActualizarCajero          127
#define IDD_D_AltaCliente               129
#define IDD_D_BajaClientes              131
#define IDD_D_ListaClientes             133
#define IDD_D_ActualizarCliente         135
#define IDD_D_AltaPromocion             137
#define IDD_D_BajaPromocion             139
#define IDD_D_ListadoPromociones        141
#define IDD_D_ActualizarPromocion       143
#define IDD_D_AltaConsumos              145
#define IDD_D_ListadoConsumo            147
#define IDR_MenuAdministradores         150
#define IDR_MenuCajeros                 151
#define IDD_D_VPantallPrincipalCajeros  152
#define IDD_Advertencia_Borrar          154
#define IDD_DIALOG1                     156
#define IDD_Adevertencia_Exit           156
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_EDIT3                       1003
#define IDC_BUTTON1                     1004
#define IDC_B_IS_IniciarSesion          1004
#define IDC_B_AU_Guardar                1004
#define IDC_B_NA_Guardar                1004
#define IDC_B_LA_Actualizar             1004
#define IDC_BUTTON2                     1005
#define IDC_S_RA                        1005
#define IDC_B_IS_RegistrarUsuario       1005
#define IDC_B_AU_Regresar               1005
#define IDC_B_NA_Regresar               1005
#define IDC_B_LA_Eliminar               1005
#define IDC_BUTTON3                     1006
#define IDC_S_RAC                       1006
#define IDC_B_IS_Salir                  1006
#define IDC_B_LA_Regresar               1006
#define IDC_B_AU_SubirFoto              1006
#define IDC_S_RANdU                     1007
#define IDC_S_RAcontra                  1008
#define IDC_E_RU_Comercio               1009
#define IDC_E_RU_NdUsuario              1010
#define IDC_E_RU_Contra                 1011
#define IDC_B_RA_Regresar               1012
#define IDC_B_RA_RegistrarUsuario       1013
#define IDC_SB_PP_InformacionDIsponible 1014
#define IDC_S_VPP_CantidadClientes      1015
#define IDC_SB_VPP_CantidadPromociones  1016
#define IDC_SB_VPP_CantidadClientes     1017
#define IDC_S_VPP_CantidadPromociones   1018
#define IDC_S_AU_Titulo                 1018
#define IDC_SB_VPP_CantidadPromocionesInA 1019
#define IDC_S_AU_NCompleto              1019
#define IDC_S_VPP_CantidadPromocionesInA 1020
#define IDC_S_AU_AUsuario               1020
#define IDC_SB_VPP_CantidadConsumos     1021
#define IDC_S_AU_Foto                   1021
#define IDC_SB_VPP_CantidadConsumos2    1022
#define IDC_E_AU_NombreCompleto         1022
#define IDC_S_VPP_CantidadConsumos      1023
#define IDC_E_AU_AliasUsuario           1023
#define IDC_S_A_TituloNuevoAdmin        1023
#define IDC_S_VPP_CantidadConsumosTotales 1024
#define IDC_S_A_NombreUsu               1024
#define IDC_S_A_NombreCompleto          1025
#define IDC_S_A_Alias                   1026
#define IDC_S_A_Contra                  1027
#define IDC_S_A_Comercio                1028
#define IDC_S_A_TipoUsu                 1029
#define IDC_S_cliente_Fecha             1029
#define IDC_E_NA_NombreUsuario          1030
#define IDC_E_NA_NombreCompleto         1031
#define IDC_E_NA_Alias                  1032
#define IDC_E_NA_Contra                 1033
#define IDC_E_NA_Comercio               1034
#define IDC_R_NA_Administrador          1035
#define IDC_E_AA_Comercio2              1035
#define IDC_E_AA_TipoUsu                1035
#define IDC_S_C_TituloNuevoCajero       1036
#define IDC_S_C_NombreUsu               1037
#define IDC_S_C_NombreCompleto          1038
#define IDC_S_C_Alias                   1039
#define IDC_S_C_Contra                  1040
#define IDC_S_C_Comercio                1041
#define IDC_S_C_TipoUsu                 1042
#define IDC_B_NC_Guardar                1043
#define IDC_B_NC_Regresar               1044
#define IDC_R_NC_Cajero                 1045
#define IDC_E_NC_Comercio               1046
#define IDC_E_NC_Contra                 1047
#define IDC_E_NC_Alias                  1048
#define IDC_E_NC_NombreCompleto         1049
#define IDC_E_NC_NombreUsuario          1050
#define IDC_LB_A_Lista                  1051
#define ID_S_LA_TituloInfoAdmiN         1052
#define IDC_E_LA_NombreUsuario          1053
#define IDC_E_LA_NombreCompleto         1054
#define IDC_E_LA_Alias                  1055
#define IDC_E_LA_Contra                 1056
#define IDC_E_LA_Comercio               1057
#define IDC_E_LA_TipoUsu                1058
#define IDC_S_LA_TipoUsu                1059
#define IDC_S_LA_Comercio               1060
#define IDC_S_LA_Contra                 1061
#define IDC_S_LA_Alias                  1062
#define IDC_S_LA_NombreCompleto         1063
#define IDC_S_LA_NombreUsu              1064
#define IDC_LB_C_Lista                  1065
#define IDC_E_LC_NombreUsuario          1066
#define IDC_E_LC_NombreCompleto         1067
#define IDC_E_LC_Alias                  1068
#define IDC_E_LC_Contra                 1069
#define IDC_E_LC_Comercio               1070
#define IDC_E_LC_TipoUsu                1071
#define IDC_S_LC_NombreUsu              1072
#define IDC_S_LC_NombreCompleto         1073
#define IDC_S_LC_Alias                  1074
#define IDC_S_LC_Contra                 1075
#define IDC_S_LC_Comercio               1076
#define IDC_S_LC_TipoUsu                1077
#define ID_S_LC_TituloInfoAdmiN         1078
#define IDC_B_LC_Actualizar             1079
#define IDC_B_LC_Eliminar               1080
#define IDC_B_LC_Regresar               1081
#define ID_S_BA_TituloInfoAdmiN         1082
#define IDC_S_BA_NombreUsu              1083
#define IDC_S_BA_NombreCompleto         1084
#define IDC_S_BA_Alias                  1085
#define IDC_S_BA_Contra                 1086
#define IDC_S_BA_Comercio               1087
#define IDC_S_BA_TipoUsu                1088
#define IDC_E_BA_NombreUsuario          1089
#define IDC_E_BA_NombreCompleto         1090
#define IDC_E_BA_Alias                  1091
#define IDC_E_BA_Contra                 1092
#define IDC_E_BA_Comercio               1093
#define IDC_E_BA_TipoUsu                1094
#define IDC_B_BA_Eliminar               1095
#define IDC_B_BA_Regresar               1096
#define ID_S_BC_TituloInfoAdmiN         1097
#define IDC_S_BC_NombreUsu              1098
#define IDC_S_BC_NombreCompleto         1099
#define IDC_S_BC_Alias                  1100
#define IDC_S_BC_Contra                 1101
#define IDC_S_BC_Comercio               1102
#define IDC_S_BC_TipoUsu                1103
#define IDC_E_BC_NombreUsuario          1104
#define IDC_E_BC_NombreCompleto         1105
#define IDC_E_BC_Alias                  1106
#define IDC_E_BC_Contra                 1107
#define IDC_E_BC_Comercio               1108
#define IDC_E_BC_TipoUsu                1109
#define IDC_B_BC_Eliminar               1110
#define IDC_B_BC_Regresar               1111
#define IDC_E_AA_NombreUsuario          1112
#define IDC_E_AA_NombreCompleto         1113
#define IDC_E_AA_Alias                  1114
#define IDC_E_AA_Contra                 1115
#define IDC_E_AA_Comercio               1116
#define IDC_S_AA_TituloNuevoAdmin       1117
#define IDC_S_AA_NombreUsu              1118
#define IDC_S_AA_NombreCompleto         1119
#define IDC_S_AA_Alias                  1120
#define IDC_S_AA_Contra                 1121
#define IDC_S_AA_Comercio               1122
#define IDC_S_AA_TipoUsu                1123
#define IDC_B_AA_Guardar                1124
#define IDC_B_AA_Regresar               1125
#define IDC_S_AC_TituloNuevoAdmin       1126
#define IDC_S_AC_NombreUsu              1127
#define IDC_S_AC_NombreCompleto         1128
#define IDC_S_AC_Alias                  1129
#define IDC_S_AC_Contra                 1130
#define IDC_S_AC_Comercio               1131
#define IDC_S_AC_TipoUsu                1132
#define IDC_E_AC_NombreUsuario          1133
#define IDC_E_AC_NombreCompleto         1134
#define IDC_E_AC_Alias                  1135
#define IDC_E_AC_Contra                 1136
#define IDC_E_AC_Comercio               1137
#define IDC_E_AC_Comercio2              1138
#define IDC_E_AC_TipoUsu                1138
#define IDC_B_AC_Guardar                1139
#define IDC_B_AC_Regresar               1140
#define IDC_L_AA_ListaUsuarios          1141
#define IDC_L_AC_ListaCajeros           1141
#define IDC_S_c_TituloNuevoCliente      1142
#define IDC_S_cliente_NombreCompleto    1143
#define IDC_E_Ncliente_NombreCompleto   1144
#define IDC_S_cliente_Alias             1145
#define IDC_E_Ncliente_Alias            1146
#define IDC_S_cliente_Telefono          1147
#define IDC_E_Ncliente_Telefono         1148
#define IDC_S_cliente_Email             1149
#define IDC_E_Ncliente_Email            1150
#define IDC_DTP_cliente_Fecha           1151
#define IDC_S_cliente_Comercio          1152
#define IDC_E_Ncliente_Comercio         1153
#define IDC_B_Ncliente_Guardar          1155
#define IDC_B_Ncliente_Regresar         1156
#define IDC_S_c_TituloBajaCliente       1158
#define IDC_S_Bcliente_NombreCompleto   1159
#define IDC_S_Bcliente_Alias            1160
#define IDC_S_Bcliente_Telefono         1161
#define IDC_S_Bcliente_Email            1162
#define IDC_S_Bcliente_Comercio         1163
#define IDC_S_Bcliente_Fecha            1164
#define IDC_E_Bcliente_NombreCompleto   1165
#define IDC_E_Bcliente_Alias            1166
#define IDC_E_Bcliente_Telefono         1167
#define IDC_E_Bcliente_Email            1168
#define IDC_E_Bcliente_Comercio         1169
#define IDC_DTP_Bcliente_Fecha          1170
#define IDC_B_Bcliente_Eliminar         1171
#define IDC_B_Bcliente_Regresar         1172
#define ID_S_lc_TituloInfoCliente       1173
#define IDC_S_lcliente_NombreCompleto   1174
#define IDC_S_lcliente_Alias            1175
#define IDC_S_lcliente_Telefono         1176
#define IDC_S_lcliente_Email            1177
#define IDC_S_lcliente_Comercio         1178
#define IDC_S_lcliente_Fecha            1179
#define IDC_E_Lcliente_NombreCompleto   1180
#define IDC_E_Lcliente_Alias            1181
#define IDC_E_Lcliente_Telefono         1182
#define IDC_E_Lcliente_Email            1183
#define IDC_E_Lcliente_Comercio         1184
#define IDC_DTP_lcliente_Fecha          1185
#define IDC_B_Lclientes_Actualizar      1188
#define IDC_B_Lclientes_Eliminar        1189
#define IDC_B_Lclientes_Regresar        1190
#define IDC_L_ac_ListaClientes          1191
#define IDC_S_ac_TituloNuevoCliente     1192
#define IDC_S_acliente_NombreCompleto   1193
#define IDC_S_acliente_Alias            1194
#define IDC_S_acliente_Telefono         1195
#define IDC_S_acliente_Email            1196
#define IDC_S_acliente_Comercio         1197
#define IDC_S_acliente_Fecha            1198
#define IDC_E_Acliente_NombreCompleto   1199
#define IDC_E_Acliente_Alias            1200
#define IDC_E_Acliente_Telefono         1201
#define IDC_E_Acliente_Email            1202
#define IDC_E_Acliente_Comercio         1203
#define IDC_DTP_Acliente_Fecha          1204
#define IDC_B_Acliente_Guardar          1205
#define IDC_B_Acliente_Regresar         1206
#define IDC_S_P_TituloNuevaPromo        1207
#define IDC_S_P_NombrePromo             1208
#define IDC_S_P_tMonto                  1209
#define IDC_S_P_PorcentajeDesc          1210
#define IDC_S_P_ActivaInactiva          1211
#define IDC_NP_Activa                   1212
#define IDC_S_P_Fecha                   1213
#define IDC_DTP_NPromociones            1214
#define IDC_B_NP_Guardar                1215
#define IDC_B_NP_Regresar               1216
#define IDC_S_P_TituloBPromo            1217
#define IDC_S_BP_NombrePromo            1218
#define IDC_S_BP_tMonto                 1219
#define IDC_S_BP_PorcentajeDesc         1220
#define IDC_S_BP_ActivaInactiva         1221
#define IDC_S_BP_Fecha                  1222
#define IDC_BC_Activa                   1223
#define IDC_DTP_BPromociones            1224
#define IDC_B_BP_Eliminar               1225
#define IDC_B_BP_Regresar               1226
#define IDC_B_LP_Eliminar               1227
#define IDC_B_LP_Regresar               1228
#define IDC_B_LP_Actualizar             1229
#define IDC_S_lP_TituloPromo            1230
#define IDC_S_LP_NombrePromo            1231
#define IDC_S_LP_tMonto                 1232
#define IDC_S_LP_PorcentajeDesc         1233
#define IDC_S_LP_ActivaInactiva         1234
#define IDC_S_LP_Fecha                  1235
#define IDC_LC_Activa                   1236
#define IDC_LPromo_Activa               1236
#define IDC_DTP_LPromociones            1237
#define IDC_S_AP_TituloBPromo           1238
#define IDC_S_AP_NombrePromo            1239
#define IDC_S_AP_tMonto                 1240
#define IDC_S_AP_PorcentajeDesc         1241
#define IDC_S_AP_ActivaInactiva         1242
#define IDC_S_AP_Fecha                  1243
#define IDC_E_AP_NombrePromo            1244
#define IDC_E_AP_Monto                  1245
#define IDC_E_AP_PorcentajeDesc         1246
#define IDC_AP_Activa                   1247
#define IDC_DTP_APromociones            1248
#define IDC_B_AP_Regresar               1249
#define IDC_B_AP_Actualizar             1250
#define IDC_E_NP_NombrePromo            1251
#define IDC_E_NP_Monto                  1252
#define IDC_E_NP_PorcentajeDesc         1253
#define IDC_S_AConsumo_Titulo           1254
#define IDC_S_AConsumo_Cliente          1255
#define IDC_S_AConsumo_Monto            1256
#define IDC_S_AConsumo_Fecha            1257
#define IDC_S_AConsumo_Subtotal         1258
#define IDC_S_AConsumo_Descuento        1259
#define IDC_S_AConsumo_Total            1260
#define IDC_E_NConsumo_Subtotal         1261
#define IDC_E_NConsumo_Descuento        1262
#define IDC_E_NConsumo_Total            1263
#define IDC_C_AConsumo_Clientes         1265
#define IDC_E_NConsumo_Monto            1266
#define IDC_DTP_NConsumo_Fecha          1267
#define IDC_B_NConsumo_Guardar          1268
#define IDC_B_NConsumo_Regresar         1269
#define IDC_LB_ListadoConsumo           1270
#define IDC_E_LConsumo_Monto            1271
#define IDC_E_LConsumo_Cliente          1273
#define IDC_DTP_LConsumo_Fecha          1274
#define IDC_E_LConsumo_Subtotal         1275
#define IDC_E_LConsumo_Descuento        1276
#define IDC_E_LConsumo_Total            1277
#define IDC_S_LConsumo_Cliente          1278
#define IDC_S_LConsumo_Monto            1279
#define IDC_S_LConsumo_Fecha            1280
#define IDC_S_LConsumo_Subtotal         1281
#define IDC_S_LConsumo_Descuento        1282
#define IDC_S_LConsumo_Total            1283
#define IDC_B_LConsumo_Guardar          1284
#define IDC_B_LConsumo_Regresar         1285
#define IDC_SB_PPC_InformacionDIsponible 1286
#define IDC_SB_VPPC_CantidadClientes    1287
#define IDC_S_VPPC_CantidadClientes     1288
#define IDC_SB_VPPC_CantidadPromociones 1289
#define IDC_S_VPPC_CantidadPromociones  1290
#define IDC_SB_VPPC_CantidadPromocionesInA 1291
#define IDC_S_VPPC_CantidadPromocionesInA 1292
#define IDC_SB_VPPC_CantidadConsumos    1293
#define IDC_S_VPPC_CantidadConsumos     1294
#define IDC_SB_VPPC_CantidadConsumos2   1295
#define IDC_S_VPPC_ConsumoTotal         1296
#define IDC_LB_cli_Lista                1297
#define IDC_LB_P_Lista                  1298
#define IDC_LB_Pbaja_Lista              1299
#define IDC_COMBO1                      1300
#define IDC_CB_IS_Comercio              1300
#define IDC_E_LPromo_NombreUsuario      1301
#define IDC_E_LPromo_NombrePromo        1301
#define IDC_E_LPromo_Monto              1302
#define IDC_E_LPromo_Descuento          1303
#define IDC_RB_NC_Administrador         1304
#define IDC_RB_NC_Cajero                1305
#define IDC_RB_NA_Administrador         1306
#define IDC_RB_NA_Cajero                1307
#define IDC_E_BPromo_NombrePromo        1308
#define IDC_E_BPromo_Monto              1309
#define IDC_E_BPromo_Descuento          1310
#define IDC_PC_IS_FotoUsu               1311
#define ID_Advertencia_B_Aceptar        1312
#define ID_Advertencia_B_Cancelar       1313
#define ID_Advertencia_Exit_Aceptar     1314
#define ID_Advertencia_Exit_Cancelar    1315
#define ID_ADMINISTRADORES_ARCHIVOSBINARIO 40021
#define ID_USUARIO_ACTUALIZARUSUARIO    40109
#define ID_USUARIO_CERRARSESI40110      40110
#define ID_USUARIO_ACTUALIZARUSUARIO40114 40114
#define ID_USUARIO_CERRARSESI40115      40115
#define ID_USUARIO_SALIR                40116
#define ID_ADMINISTRADORES_ALTADEADMINISTRADOR 40117
#define ID_ADMINISTRADORES_LISTADODEADMINISTRADORES 40118
#define ID_CAJEROS_ALTADECAJEROS        40119
#define ID_CAJEROS_LISTADODE            40120
#define ID_CLIENTES_ALTADECLIENTE       40121
#define ID_CLIENTES_LISTADODECLIENTE    40122
#define ID_PROMOCIONES_ALTADEPROMOCI40123 40123
#define ID_PROMOCIONES_BAJADEPROMOCI40124 40124
#define ID_PROMOCIONES_LISTADODEPROMOCIONES 40125
#define ID_CONSUMOS_ALTADECONSUMO       40126
#define ID_CONSUMOS_LISTADECONSUMOS     40127
#define ID_MA_Consumos_ListaConsumos    40128
#define ID_MA_Consumo_AltaConsumo       40129
#define ID_MA_P_ListaPromos             40130
#define ID_MA_P_BajaPromo               40131
#define ID_MA_P_AltaPromo               40132
#define ID_MA_c_ListaClientes           40133
#define ID_MA_c_AltaCliente             40134
#define ID_MA_C_ListaCajeros            40135
#define ID_MA_A_ListaAdmins             40136
#define ID_MA_C_AltaCajeros             40137
#define ID_MA_A_AltaAdmin               40138
#define ID_MA_U_Salir                   40139
#define ID_MA_U_CerrarSesion            40140
#define ID_MA_U_ActualizarUsuario       40141
#define ID_USUARIO_ACTUALIZARUSUARIO40142 40142
#define ID_USUARIO_CERRARSESI40143      40143
#define ID_USUARIO_SALIR40144           40144
#define ID_CLIENTES_ALTADECLIENTES      40145
#define ID_CLIENTES_LISTADODECLIENTES   40146
#define ID_CLIENTES_ACTUALIZARINFORMACI40147 40147
#define ID_PROMOCIONES_LISTADODEPROMOCI40148 40148
#define ID_CONSUMO_ALTADECONSUMOS       40149
#define ID_CONSUMO_LISTADODECONSUMOS    40150
#define ID_MC_U_ActualizarUsuario       40151
#define ID_MC_U_CerrarSesion            40152
#define ID_MC_U_Salir                   40153
#define ID_MC_c_AltaClientes            40154
#define ID_MC_c_ListaClientes           40155
#define ID_MC_c_ActualizarClientes      40156
#define ID_MC_P_ListaPromos             40157
#define ID_MC_Consumo_AltaConsumo       40158
#define ID_MC_Consumo_ListaConsumos     40159

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         40160
#define _APS_NEXT_CONTROL_VALUE         1316
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
